name: adminer
services:
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - target: 8080
        published: 8181
        protocol: tcp
    restart: unless-stopped
    x-casaos:
      ports:
        - container: "8080"
          description:
            en_us: Adminer HTTP Port
            
    network_mode: bridge

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: adminer
  author: Cp0204
  category: Database
  description:
    en_us: Adminer is a database management tool that allows you to manage your databases with a simple and intuitive interface.
      developer: Adminer
  icon: https://filedn.com/ltuKYRdlbf4BG2UkSiE8r7b/GITHUB/CASAOS/BCTCasaOS-AppStore-Play-main/Apps/adminer/icon.png
  screenshot_link:
    - https://filedn.com/ltuKYRdlbf4BG2UkSiE8r7b/GITHUB/CASAOS/BCTCasaOS-AppStore-Play-main/Apps/adminer/screenshot-1.png
  tagline:
    en_us: Database management tool
     title:
    en_us: Adminer
  index: /
  port_map: "8181"
