name: palworld-server
services:
  palworld-server:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
      - 25575:25575/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=8211 #
      - PLAYERS=32 #
      - MULTITHREADING=true
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - TZ=Australia/Melbourne
      - COMMUNITY=True  # Will require Server password is specified above
      - SERVER_NAME="BCT Pal World"
      - SERVER_PASSWORD="BCTWorld" #
      - ADMIN_PASSWORD="BCTWorldAdmin"
    volumes:
      - /DATA/AppData/palworld-server:/palworld/
    network_mode: bridge
    deploy:
      resources:
        reservations:
          memory: 4096M

x-casaos:
  architectures:
    - amd64
    - arm64
  main: palworld-server
  store_app_id: palworld-server
  category: Beyond Cloud Technology
  author: BCT
  developer: thijsvanloef
  icon: https://filedn.com/ltuKYRdlbf4BG2UkSiE8r7b/GITHUB/CASAOS/BCTCasaOS-AppStore-Play-main/Apps/palworld-server/icon.png
  screenshot_link:
    - https://filedn.com/ltuKYRdlbf4BG2UkSiE8r7b/GITHUB/CASAOS/BCTCasaOS-AppStore-Play-main/Apps/palworld-server/screenshot-1.png
    - https://filedn.com/ltuKYRdlbf4BG2UkSiE8r7b/GITHUB/CASAOS/BCTCasaOS-AppStore-Play-main/Apps/palworld-server/screenshot-2.png
    - https://filedn.com/ltuKYRdlbf4BG2UkSiE8r7b/GITHUB/CASAOS/BCTCasaOS-AppStore-Play-main/Apps/palworld-server/screenshot-3.png
  thumbnail: https://filedn.com/ltuKYRdlbf4BG2UkSiE8r7b/GITHUB/CASAOS/BCTCasaOS-AppStore-Play-main/Apps/palworld-server/thumbnail.png
  description:
    en_us: Get started with hosting your own Palworld Dedicated Server. Palworld is an action-adventure, survival, and monster-taming game created and published by Japanese developer Pocket Pair. The game is set in an open world populated with animal-like creatures called "Pals", which players can battle and capture to use for base building, traversal, and combat.
  tagline:
    en_us: Easily run a Palworld Dedicated Server
    
  title:
    en_us: Palworld Dedicated Server BCT
    
  tips:
    before_install:
      en_us: |
        This application is a game private service with high performance requirements:

        | Resources | Minimum | Recommended |
        | ---- | ---- | ---- |
        | CPU | 4 core | 4+ core |
        | RAM | 16GB | 32GB+ |
        | Storage | 8GB | 20GB |

        > Has been tested 1 player logged in to play 2GB RAM usage.

        Environment variables that should be modified after installation:

        | Variables | Information | Defaults |
        | ---- | ---- | ------ |
        | SERVER_NAME | Server Name | `BCT Pal World` |
        | SERVER_PASSWORD | Server Password | `BCTWorld` |
        | ADMIN_PASSWORD | Server administrator password | `BCTWorldAdmin` |

        Other parameters of the game server can be set in the environment variables, please read the [documentation](https://github.com/thijsvanloef/palworld-server-docker?tab=readme-ov-file#editing-server-settings).

  port_map: ''
  scheme: http
  index: /
