name: moviepilot
services:
  moviepilot:
    stdin_open: true
    tty: true
    container_name: moviepilot
    hostname: moviepilot
    # networks:
    #   - moviepilot
    ports:
      - target: 3000
        published: "3000"
        protocol: tcp
    volumes:
      - "/DATA/Media:/media"
      - "/DATA/AppData/moviepilot/config:/config"
      - "/DATA/AppData/moviepilot/core:/moviepilot/.cache/ms-playwright"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - "NGINX_PORT=3000"
      - "PORT=3001"
      - "PUID=0"
      - "PGID=0"
      - "UMASK=000"
      - "TZ=Asia/Shanghai"
      - "AUTH_SITE=iyuu"
      - "IYUU_SIGN=xxxx"
      - "SUPERUSER=admin"
      - "API_TOKEN=moviepilot"
    restart: unless-stopped
    image: jxxghp/moviepilot:latest
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge

# networks:
#   moviepilot:
#     name: moviepilot

x-casaos:
  architectures:
    - arm64
    - amd64
  main: moviepilot
  store_app_id: moviepilot
  author: CasaOS Team & Cp0204
  category: Beyond Cloud Technology
  developer: jxxghp
  tagline:
    en_us: NAS Media Library Automation Management Tool
    zh_cn: NAS媒体库自动化管理工具
  description:
    en_us: MoviePilot is a video management tool that can automatically download and manage movies. **The MoviePilot V1 version stops feature updates, only fixes major bugs and simultaneously updates site resource packs. The V2 version has added a number of new features. Some functions have been redesigned and developed using independent scenarios. They cannot be automatically upgraded through the V1 version. They are also incompatible with the configuration and database files of the old version.**
    zh_cn: MoviePilot 是一个视频管理工具，可以自动下载和管理电影。**MoviePilot V1版本停止功能更新，仅修复重大Bug以及同步更新站点资源包。V2版本新增多项新特性，部分功能重新设计开发，使用独立境像，无法通过V1版本自动升级，同时也不兼容旧版本配置和数据库文件。**
  title:
    en_us: MoviePilot
  icon: https://filedn.com/ltuKYRdlbf4BG2UkSiE8r7b/GITHUB/CASAOS/BCTCasaOS-AppStore-Play-main/Apps/moviepilot/icon.png
  screenshot_link:
    - https://filedn.com/ltuKYRdlbf4BG2UkSiE8r7b/GITHUB/CASAOS/BCTCasaOS-AppStore-Play-main/Apps/moviepilot/screenshot-1.png
    - https://filedn.com/ltuKYRdlbf4BG2UkSiE8r7b/GITHUB/CASAOS/BCTCasaOS-AppStore-Play-main/Apps/moviepilot/screenshot-2.png
  index: /
  port_map: "3000"
  tips:
    before_install:
      en_us: |
        **The MoviePilot V1 version stops feature updates, only fixes major bugs and simultaneously updates site resource packs. The V2 version has added a number of new features. Some functions have been redesigned and developed using independent scenarios. They cannot be automatically upgraded through the V1 version. They are also incompatible with the configuration and database files of the old version.**

        ## Default Account

        | Username | Password |
        |----------|----------|
        | `admin` | Get from log |

        Please note that this software is a bit complicated, you need to read the [documentation](https://wiki.movie-pilot.org/configuration)
      zh_cn: |
        **MoviePilot V1版本停止功能更新，仅修复重大Bug以及同步更新站点资源包。V2版本新增多项新特性，部分功能重新设计开发，使用独立境像，无法通过V1版本自动升级，同时也不兼容旧版本配置和数据库文件。**

        ## 默认账号

        | 用户名 | 密码 |
        |----------|----------|
        | `admin` | 从日志中获取 |

        注意本软件比较复杂，你需要阅读[文档](https://wiki.movie-pilot.org/configuration)
